name: Deploy Sentiment Analysis to AWS

on:
  push:
    branches:
      - master  # o la rama que estés usando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install Serverless plugins
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy with Serverless
        run: serverless deploy --stage test --verbose --force
